name: ItemLogger
main: com.pandemoneus.itemLogger.ItemLogger
version: 1.03
author: 'Pandemoneus'

commands:
    itemlogger:
        description: ItemLogger
        usage: |
               /<command>
    il:
        description: ItemLogger
        usage: |
               /<command>